services:
  - type: web
    name: hrm-soft-api
    env: python
    region: oregon
    plan: free
    runtime: python-3.9
    rootDir: HRM_SOFT
    buildCommand: "pip install -r ../requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn HRM_SOFT.HRM_SOFT.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DJANGO_SETTINGS_MODULE
        value: HRM_SOFT.settings
      - key: PYTHONUNBUFFERED
        value: true
